## Best practice recommendations for Tabular Data Processing:

 

| Order | Best Practice | Implementation |
| :---         |     :---      |          :--- |
| 1   | Do not change any original data     | Mark all original data as "read-only"    |
| 2     | Assign unique ordinals to each row       | A new right most column      |
| 3     | For each derived/processed column add a new column       | A new right most column      |
| 4     | Use visual cues for types and provenance of data |Different column heading highlights for read-only, derived data and groups of columns | A new right most column      |
| 5     | Identify key fields in the data | Identify identifiers|
| 6     | Mark all missing data in new columns | Explicitly state what the "N/A" data constants are and use "token" that is not valid data in any field.|
| 7     | Identify duplicates  | Explicitly state how duplicates are dealt with|
| 8     | Identify inconsistent data (controlled vocabulary inconsistencies) | Construct lookup tables for many to one mappings |
| 9     | Standardize values: units | Localization in office documents|
| 10     | Standardize values: dates | Localization in office documents|
| 11     | Standardize values: names | People, places, controlled vocabulary|
